Repository transcend-tn/PFE-2020, pull requests merged in 2020-11, with the labels that each got.

#100 feat(client): profile collaboration tab
  packages/client/src/components/CollaborationRequest.tsx
  packages/client/src/constants/uris.ts
  packages/client/src/pages/DocumentPage/containers/TeamMembersListContainer.tsx
  packages/client/src/pages/ProfilePage/ProfilePage.tsx
  packages/client/src/pages/ProfilePage/containers/CollaborationRequestContainer.tsx
  packages/client/src/services/collaboration.service.ts
Labels: frontend

#109 fix:(client): edit password
  packages/client/src/components/ChangePasswordForm.tsx
  packages/client/src/components/SignUpForm.tsx
  packages/client/src/pages/EditProfilePage/containers/ChangePasswordFormContainer.tsx
  packages/client/src/services/user.service.ts
Labels: frontend

#107 feat(client): 404 page
  packages/client/src/pages/PageIntrouvablePage.tsx
  packages/client/src/root/routes.ts
Labels: frontend

#105 feat: store json body
  packages/api/src/document/docuemnt.model.ts
Labels: backend

#106 refactor(api): add comment on request
  packages/api/src/comment/comment.controller.ts
  packages/api/src/comment/comment.model.ts
  packages/api/src/comment/comment.service.ts
Labels: backend

#115 fix: redirection profile
  packages/client/src/components/NewDocument.tsx
Labels: frontend

#110 fix(client): Typo
  packages/client/src/components/ChangePasswordForm.tsx
  packages/client/src/components/EditProfileForm.tsx
Labels: frontend, wip

#112 feat(client): formattage date
  packages/api/src/document/document.controller.ts
  packages/client/package.json
  packages/client/src/components/DocumentHeader.tsx
  packages/client/src/components/MessageCard.tsx
  packages/client/src/pages/DocumentPage/DocumentPage.tsx
  yarn.lock
Labels: frontend, wip

#116 feat(client): commentaires document / request
  packages/client/src/components/MessageForm.tsx
  packages/client/src/constants/uris.ts
  packages/client/src/pages/PropositionDetailsPage/Containers/MessageFormContainer.tsx
  packages/client/src/pages/PropositionDetailsPage/Containers/MessageListContainer.tsx
  packages/client/src/pages/PropositionDetailsPage/PropositionDetailsPage.tsx
  packages/client/src/services/comment.service.ts
Labels: frontend

#121 ⚡ refactor: show document
  packages/api/src/document/document.service.ts
Labels: backend

#122 feat: list favorite
  packages/api/src/document/document.service.ts
  packages/api/src/favorite/favorite.controller.ts
  packages/api/src/favorite/favorite.module.ts
  packages/api/src/favorite/favorite.service.ts
Labels: backend

#113 feat(client): page profile favoris
  packages/api/src/favorite/favorite.controller.ts
  packages/api/src/favorite/favorite.entity.ts
  packages/api/src/favorite/favorite.service.ts
  packages/api/src/users/user.entity.ts
  packages/client/src/components/FavorisCard.tsx
  packages/client/src/pages/ProfilePage/ProfilePage.tsx
  packages/client/src/pages/ProfilePage/containers/DocumentsListContainer.tsx
  packages/client/src/pages/ProfilePage/containers/FavorisCardContainer.tsx
  packages/client/src/pages/ProfilePage/containers/FavorisListeContainer.tsx
  packages/client/src/root/App.tsx
  packages/client/src/services/document.service.ts
  packages/client/src/services/favorite.service.ts
Labels: blocked, frontend
