Repository transcend-tn/PFE-2020, pull requests merged in 2020-10, with the labels that each got.

#2 setup frontend
  api/src/main.ts
  client/.gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/components/VisitCard/VisitCard.tsx
  client/src/components/VisitCard/index.tsx
  client/src/index.tsx
  client/src/interfaces/children.interface.ts
  client/src/models/injections.model.ts
  client/src/models/user.model.ts
  client/src/react-app-env.d.ts
  client/src/root/App.tsx
  client/src/root/store.ts
  client/src/root/styles/index.scss
  client/src/serviceWorker.ts
  client/src/services/user.service.ts
  client/src/setupTests.ts
  client/tsconfig.json
  client/yarn.lock
Labels: frontend

#3 api call
  client/src/components/VisitCard/VisitCard.tsx
  client/src/components/VisitCard/index.tsx
  client/src/hooks/store.hooks.ts
  client/src/root/App.tsx
Labels: frontend

#4 Feature/auth
  api/package.json
  api/src/app.module.ts
  api/src/config/typeorm.config.ts
  api/src/users/data.json.ts
  api/src/users/dto/auth-credentials.dto.ts
  api/src/users/dto/createUser.dto.ts
  api/src/users/user.entity.ts
  api/src/users/user.repository.ts
  api/src/users/users.controller.ts
  api/src/users/users.module.ts
  api/src/users/users.service.ts
  api/yarn.lock
  client/package.json
  client/src/components/layouts/withCenter.tsx
  client/src/components/layouts/withMain.tsx
  client/src/constants/config.ts
  client/src/constants/uris.ts
  client/src/interfaces/signIn.interface.ts
  client/src/interfaces/signup.interface.ts
  client/src/models/user.model.ts
  client/src/pages/Profile.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/src/root/App.tsx
  client/src/root/routes.ts
  client/src/root/store.ts
  client/src/root/styles/index.scss
  client/src/services/user.service.ts
  client/yarn.lock
Labels: backend

#5 Fix : api & client ports
  api/package.json
  client/package.json
Labels: enhancement

#9 CollaborationRequest
  client/src/components/CollaborationRequest.tsx
  client/src/pages/Requests.tsx
  client/src/root/routes.ts
Labels: frontend

#8 Favoris
  client/src/components/Favoris.tsx
  client/src/pages/FavorisPage.tsx
  client/src/root/routes.ts
Labels: frontend

#6 Forget Password
  client/src/components/ForgetPassword.tsx
  client/src/root/routes.ts
Labels: frontend

#11 fix : route.ts
  client/src/root/routes.ts
Labels: frontend

#10 Setup : cross-env
  api/package.json
  api/yarn.lock
  client/package.json
  client/yarn.lock
Labels: backend, enhancement, frontend

#13 welcome
  client/package.json
  client/src/components/welcome.tsx
  client/src/root/routes.ts
Labels: frontend

#14 Fix Welcome Component
  client/src/components/Welcome.tsx
Labels: bug

#12 yarn workspaces
  .gitignore
  api/package.json
  api/yarn.lock
  client/package.json
  package.json
  yarn.lock
Labels: backend, enhancement, frontend

#18 ProfileCard
  client/src/components/ProfileCard.tsx
  client/src/root/routes.ts
Labels: frontend

#19 add img props
  client/src/components/ProfileCard.tsx
Labels: frontend

#20 fix: design & routing
  client/public/index.html
  client/src/components/ForgetPassword.tsx
  client/src/components/Welcome.tsx
  client/src/components/layouts/withMain.tsx
  client/src/pages/SignIn.tsx
  client/src/root/App.tsx
  client/src/root/routes.ts
Labels: frontend

#25 wip: editorconfig
  .commitlintrc
  .czrc
  .editorconfig
  .gitignore
  .huskyrc
  .lintstagedrc
  .nvmrc
  .yarnrc
  api/package.json
  client/.prettierrc
  client/package.json
  client/src/components/CollaborationRequest.tsx
  client/src/components/FavorisCard.tsx
  client/src/components/ProfileCard.tsx
  client/src/components/Welcome.tsx
  client/src/components/layouts/withCenter.tsx
  client/src/components/layouts/withMain.tsx
  client/src/index.tsx
  client/src/pages/DocumentsPage.tsx
  client/src/pages/EditProfilePage.tsx
  client/src/pages/FavorisPage.tsx
  client/src/pages/ForgetPasswordPage.tsx
  client/src/pages/NewDocumentsPage.tsx
  client/src/pages/RequestsPage.tsx
  client/src/pages/SignInPage.tsx
  client/src/pages/SignUpPage.tsx
  client/src/root/App.tsx
  package.json
  yarn.lock
Labels: backend, chore, frontend

#28 Hotfix
  package.json
Labels: chore

#29 MemberCard
  client/src/components/MemberCard.tsx
Labels: frontend

#32 feat(pages): documentspages.tsx
  client/src/pages/DocumentsPage.tsx
Labels: frontend

#33 create : changepasswordForm
  client/src/components/ChangePasswordForm.tsx
  client/src/interfaces/ChangePassword.interface.ts
Labels: frontend

#34 chore(server): setup json-server
  api/db.json
  api/package.json
  api/server.js
  package.json
  yarn.lock
Labels: chore

#39 feat(pages): react draft wysiwyg
  api/db.json
  client/package.json
  client/src/pages/NewDocumentsPage.tsx
  yarn.lock
Labels: frontend

#38 feat(components): deleteaccountcard.tsx
  client/src/components/DeleteAccountCard.tsx
Labels: frontend

#36 feat(components): editprofileform.tsx
  client/src/components/EditProfileForm.tsx
  client/src/interfaces/EditProfileForm.interface.ts
  client/src/pages/NewDocumentsPage.tsx
Labels: frontend

#35 feat(components): historycard.tsx
  client/src/components/HistoryCard.tsx
Labels: frontend

#42 feat(components): messagecard.tsx
  client/src/components/MessageCard.tsx
  client/src/pages/NewDocumentsPage.tsx
Labels: frontend

#41 feat(components): MessageForm
  client/src/components/MessageForm.tsx
  client/src/interfaces/MessageForm.ts
  client/src/pages/NewDocumentsPage.tsx
Labels: frontend

#43 feat(components): Vote
  client/src/components/Vote.tsx
Labels: frontend

#44 feat(components): documentheader.tsx
  client/src/components/DocumentHeader.tsx
  client/src/pages/EditDocumentPage.tsx
  client/src/root/routes.ts
Labels: frontend

#46 feat(pages): editprofilepage
  client/src/components/EditProfileForm.tsx
  client/src/pages/EditProfilePage.tsx
Labels: frontend

#45 feat(components): PropositionCard
  client/src/components/PropositionCard.tsx
  client/src/pages/PropositionModificationPage.tsx
  client/src/root/routes.ts
Labels: frontend

#54 ✨ Team Members List
  client/src/components/CollaborationRequest.tsx
  client/src/components/DeleteAccountCard.tsx
  client/src/components/EditProfileForm.tsx
  client/src/components/FavorisCard.tsx
  client/src/components/MemberCard.tsx
  client/src/components/ProfileCard.tsx
  client/src/components/TeamMembersList.tsx
  client/src/pages/EditProfilePage.tsx
  client/src/pages/NewDocumentPage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/root/routes.ts
Labels: frontend

#53 ✨ Proposition List Component
  client/src/components/CollaborationRequest.tsx
  client/src/components/DeleteAccountCard.tsx
  client/src/components/ProfileCard.tsx
  client/src/components/PropositionCard.tsx
  client/src/components/PropositionList.tsx
Labels: frontend

#52 ✨ History List Component
  client/src/components/HistoryCard.tsx
  client/src/components/HistoryList.tsx
Labels: frontend

#51 ✨ MessageList component
  client/src/components/MessageCard.tsx
  client/src/components/MessageList.tsx
Labels: frontend

#55 style: welcome page
  client/src/components/HistoryCard.tsx
  client/src/components/SignInForm.tsx
  client/src/components/SignUpForm.tsx
  client/src/components/Welcome.tsx
Labels: frontend

#50 ✨ User default profile image
  api/src/users/user.entity.ts
  api/src/users/users.service.ts
  client/public/favicon.ico
  client/public/index.html
  client/public/user.png
Labels: backend, frontend

#40 ⚡ JWT Strategy + GetUser decorator
  api/src/users/get-user.decorator.ts
  api/src/users/jw.strategy.ts
  api/src/users/users.controller.ts
  api/src/users/users.module.ts
Labels: backend

#49 ⚡ Mangoose Setup + document CRUD
  api/package.json
  api/src/app.module.ts
  api/src/document/docuemnt.model.ts
  api/src/document/document.controller.ts
  api/src/document/document.module.ts
  api/src/document/document.service.ts
  api/src/document/dto/document.dto.ts
  yarn.lock
Labels: backend

#61 ⚡ Proposition de Modification
  packages/client/src/pages/PropositionDetailsPage.tsx
  packages/client/src/root/routes.ts
Labels: frontend

#59 ⚡ Document page
  packages/client/src/components/DocumentHeader.tsx
  packages/client/src/components/EditProfileForm.tsx
  packages/client/src/components/FavorisCard.tsx
  packages/client/src/components/HistoryCard.tsx
  packages/client/src/components/HistoryList.tsx
  packages/client/src/components/MessageForm.tsx
  packages/client/src/components/PropositionCard.tsx
  packages/client/src/components/PropositionList.tsx
  packages/client/src/components/TeamMembersList.tsx
  packages/client/src/pages/DocumentPage.tsx
  packages/client/src/root/routes.ts
  packages/client/src/root/styles/index.scss
Labels: enhancement, frontend

#60 feat(components): link
  packages/client/src/components/CollaborationRequest.tsx
  packages/client/src/components/FavorisCard.tsx
Labels: frontend

#63 ⚡ Edit Document
  packages/client/src/pages/EditDocumentPage.tsx
Labels: frontend

#65 feat(api): create document
  packages/api/src/document/docuemnt.model.ts
  packages/api/src/document/document.controller.ts
  packages/api/src/document/document.module.ts
  packages/api/src/document/document.service.ts
  packages/api/src/users/user.entity.ts
Labels: backend

#66 Get User By Id
  packages/api/src/users/user.entity.ts
  packages/api/src/users/users.controller.ts
  packages/api/src/users/users.service.ts
Labels: backend

#67 feat(api): edit user
  packages/api/src/users/users.controller.ts
  packages/api/src/users/users.service.ts
Labels: backend

#68 fix(client): proposition-details
  packages/client/src/pages/EditDocumentPage.tsx
  packages/client/src/pages/PropositionDetailsPage.tsx
Labels: enhancement, frontend

#69 chore: move dots config to package.json
  .commitlintrc
  .czrc
  .huskyrc
  .lintstagedrc
  .nvmrc
  .yarnrc
  packages/client/.prettierrc
  packages/client/package.json
Labels: chore

#70 feat: wip
  packages/api/src/document/document.controller.ts
  packages/client/package.json
  packages/client/src/config/axios.ts
  packages/client/src/constants/uris.ts
  packages/client/src/pages/NewDocumentPage.tsx
  packages/client/src/pages/ProfilePage/ProfilePage.tsx
  packages/client/src/pages/ProfilePage/containers/DocumentsList.tsx
  packages/client/src/root/App.tsx
  packages/client/src/root/routes.ts
  packages/client/src/root/styles/index.scss
  packages/client/src/services/document.service.ts
  packages/client/src/services/user.service.ts
  yarn.lock
Labels: frontend

#71 feat: document-get-by-owner
  packages/client/src/pages/ProfilePage/containers/DocumentsList.tsx
  packages/client/src/services/document.service.ts
Labels: frontend

#75 feat: user-get-by-id
  packages/client/src/constants/uris.ts
  packages/client/src/services/user.service.ts
Labels: frontend

#74 feat: document-get-by-id
  packages/client/src/constants/uris.ts
  packages/client/src/services/document.service.ts
Labels: frontend

#77 ⚡ Favorite & Comment Core
  packages/api/src/app.module.ts
  packages/api/src/comment/comment.controller.ts
  packages/api/src/comment/comment.model.ts
  packages/api/src/comment/comment.module.ts
  packages/api/src/comment/comment.service.ts
  packages/api/src/favorite/favorite.controller.ts
  packages/api/src/favorite/favorite.entity.ts
  packages/api/src/favorite/favorite.module.ts
  packages/api/src/favorite/favorite.repository.ts
  packages/api/src/favorite/favorite.service.ts
  packages/api/src/users/user.entity.ts
  packages/client/src/components/MessageForm.tsx
  packages/common/src/comment.interface.ts
  yarn.lock
Labels: backend

#79 feat(api): comment by doc id
  packages/api/src/comment/comment.controller.ts
  packages/api/src/comment/comment.service.ts
Labels: backend

#88 ⚡ Document Edit Request
  packages/api/src/app.module.ts
  packages/api/src/request/request.controller.ts
  packages/api/src/request/request.model.ts
  packages/api/src/request/request.module.ts
  packages/api/src/request/request.service.ts
Labels: backend

#87 ⚡ Collaboration Services
  packages/api/src/app.module.ts
  packages/api/src/collaboration/collaboration.controller.ts
  packages/api/src/collaboration/collaboration.model.ts
  packages/api/src/collaboration/collaboration.module.ts
  packages/api/src/collaboration/collaboration.service.ts
  packages/api/src/document/document.service.ts
Labels: backend

#86 feat: favorite-remove
  packages/client/src/components/FavorisCard.tsx
  packages/client/src/constants/uris.ts
  packages/client/src/pages/ProfilePage/containers/FavorisCardContainer.tsx
  packages/client/src/services/favorite.service.ts
Labels: frontend

#82 feat: user-change-password
  packages/client/src/components/ChangePasswordForm.tsx
  packages/client/src/constants/uris.ts
  packages/client/src/pages/EditProfilePage/containers/ChangePasswordFormContainer.tsx
  packages/client/src/services/user.service.ts
Labels: frontend

#84 feat: favoris-add-favoris
  packages/client/src/pages/ProfilePage/containers/FavorisCardContainer.tsx
  packages/client/src/services/favorite.service.ts
Labels: frontend

#83 feat(client): comment create
  packages/client/src/services/comment.service.ts
Labels: frontend

#73 feat:document-update
  packages/client/src/services/document.service.ts
  packages/common/src/document.interface.ts
Labels: frontend, wip

#89 fix: titre demande modification
  packages/client/src/pages/EditDocumentPage/EditDocumentContainer.tsx
Labels: frontend

#90 refactor(client): vote
  packages/client/src/components/Vote.tsx
  packages/client/src/pages/PropositionDetailsPage.tsx
Labels: frontend

#92 feat: demande-modification
  packages/client/src/constants/uris.ts
  packages/client/src/pages/DocumentPage/containers/TeamMembersListContainer.tsx
  packages/client/src/services/collaboration.service.ts
Labels: frontend

#97 fix: vote
  packages/client/src/components/Vote.tsx
Labels: frontend

#93 ⚡ refactor(api): show team members
  packages/api/src/collaboration/collaboration.module.ts
  packages/api/src/collaboration/collaboration.service.ts
Labels: backend

#95 ⚡ Setup Vote System
  packages/api/src/app.module.ts
  packages/api/src/collaboration/collaboration.service.ts
  packages/api/src/request/request.service.ts
  packages/api/src/vote/vote.controller.ts
  packages/api/src/vote/vote.model.ts
  packages/api/src/vote/vote.module.ts
  packages/api/src/vote/vote.service.ts
Labels: backend

#96 fix: registration-redirection
  packages/client/src/components/SignUpForm.tsx
Labels: frontend

#99 feat(client): propositions list
  packages/client/src/components/PropositionCard.tsx
  packages/client/src/components/PropositionList.tsx
  packages/client/src/constants/uris.ts
  packages/client/src/pages/DocumentPage/containers/PropositionListContainer.tsx
  packages/client/src/pages/PropositionDetailsPage/PropositionDetailsPage.tsx
  packages/client/src/root/routes.ts
  packages/client/src/services/request.service.ts
Labels: frontend

#101 ⚡ Refector : only team members can request
  packages/api/src/request/request.controller.ts
  packages/api/src/request/request.model.ts
  packages/api/src/request/request.module.ts
  packages/api/src/request/request.service.ts
  packages/common/src/index.ts
  packages/common/src/request.interface.ts
Labels: backend

#104 feat(api): soft delete
  packages/api/src/users/user.entity.ts
  packages/api/src/users/users.controller.ts
  packages/api/src/users/users.service.ts
Labels: backend
